import os
import boto3
import dotenv

dotenv.load_dotenv()

REGION_NAME = os.environ.get("REGION_NAME")
BUCKET_NAME = os.environ.get("BUCKET_NAME")
DATABASE_NAME = os.environ.get("DATABASE_NAME")
AWS_ACCESS_KEY = os.environ.get("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
BUCKET_FOLDER_HOSPITAL_BEDS = os.environ.get("BUCKET_FOLDER_HOSPITAL_BEDS")
BUCKET_FOLDER_CASES_AND_DEATHS = os.environ.get("BUCKET_FOLDER_CASES_AND_DEATHS")
BUCKET_FOLDER_GLOBAL_DEATHS = os.environ.get("BUCKET_FOLDER_GLOBAL_DEATHS")
BUCKET_FOLDER_VACCINATED_PER_HUNDRED = os.environ.get("BUCKET_FOLDER_VACCINATED_PER_HUNDRED")
BUCKET_FOLDER_VACCINES_AND_VACCINATED = os.environ.get("BUCKET_FOLDER_VACCINES_AND_VACCINATED")

session = boto3.Session(
    region_name=REGION_NAME,
    aws_access_key_id=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY
)